// Branding and installed capabilities. Generated by the wizard; no secrets here.
export const project = {
  name: "My Product",
  description: "Un nuovo progetto.",
  locale: "it",
  preset: "landing",
  provider: "none",
  allowSignup: true,
} as const;
